name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python train_model.py

      - name: Run tests
        run: python test_model.py

      - name: Upload model to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: model.pkl
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}